# Generated by Django 4.2.17 on 2024-12-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
