# Generated by Django 4.2.17 on 2024-12-27 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
        ('Orders', '0002_orders_order_date_orders_order_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='product_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Products.product'),
        ),
    ]
