# Generated by Django 4.2.17 on 2024-12-27 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Discounts', '0001_initial'),
        ('Orders', '0004_orders_order_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='discount_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Discounts.discount'),
        ),
    ]
