# Generated by Django 4.2.17 on 2024-12-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('discount_id', models.AutoField(primary_key=True, serialize=False)),
                ('discount_code', models.CharField(max_length=100)),
                ('discount_amount', models.FloatField()),
            ],
        ),
    ]
