# Generated by Django 4.2.17 on 2024-12-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discounts', '0002_rename_discount_amount_discount_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
